apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: os-nodejs
  name: os-nodejs
  namespace: osdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-nodejs  
  template:
    metadata:
      labels:
        app: os-nodejs
    spec:    
      containers:
        - name: os-nodejs        
          image: alkesh/os-nodejs:v1
          livenessProbe:
            httpGet:
              port: http
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3          
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 3
          ports:
          - containerPort: 8082
      
